### ISSUE TITLE
Step throws NPE when no rows are sent to the step

### ISSUE THREAD

**Issue by matthewtckr** [mattyb149/pdi-superlative-plugin#2]
```
2019/12/06 06:42:05 - Earliest response_select.0 - ERROR (version 8.1.0.0-365, build 8.1.0.0-365 from 2018-04-30 09.42.24 by buildguy) : Unexpected error
2019/12/06 06:42:05 - Earliest response_select.0 - ERROR (version 8.1.0.0-365, build 8.1.0.0-365 from 2018-04-30 09.42.24 by buildguy) : java.lang.NullPointerException
2019/12/06 06:42:05 - Earliest response_select.0 -     at org.pentaho.di.trans.steps.superlative.SuperlativeFilter.processRow(SuperlativeFilter.java:84)
2019/12/06 06:42:05 - Earliest response_select.0 -     at org.pentaho.di.trans.step.RunThread.run(RunThread.java:62)
2019/12/06 06:42:05 - Earliest response_select.0 -     at java.lang.Thread.run(Thread.java:748)
2019/12/06 06:42:05 - Earliest response_select.0 - Finished processing (I=0, O=0, R=0, W=0, U=0, E=1)
```

**Comment by matthewtckr** [comment]
#3 Pull request
